version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=W3@k{@psw0rd!7
      - MYSQL_DATABASE=love_music
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    image: tunify
    container_name: tunify
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/love_music?createDatabaseIfNotExist=true&useSSL=true
      - SPRING_DATASOURCE_PASSWORD=Mz8@Q#2hG5&X7u!p
      - SPRING_DATASOURCE_USERNAME=app_user
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  mysql-data:
